# Generated by Django 4.2 on 2023-12-06 15:19

from django.db import migrations
import text_to_pdf.models


class Migration(migrations.Migration):

    dependencies = [
        ('text_to_pdf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='texttopdf',
            name='file_size',
            field=text_to_pdf.models.FileSizeField(blank=True, editable=False, null=True),
        ),
    ]
