# Generated by Django 4.2 on 2023-12-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_to_pdf', '0002_texttopdf_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texttopdf',
            name='file',
            field=models.FileField(upload_to='text-to-pdf/'),
        ),
    ]
