# Generated by Django 4.2 on 2023-12-06 18:54

import core.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_to_pdf', '0003_alter_texttopdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texttopdf',
            name='file',
            field=models.FileField(storage=core.storage_backends.PublicMediaStorage(), upload_to='text-to-pdf/'),
        ),
    ]
