# Generated by Django 4.2 on 2023-12-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_to_pdf', '0004_alter_texttopdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='texttopdf',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
