# Generated by Django 4.2 on 2023-12-07 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text_to_pdf', '0005_texttopdf_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='texttopdf',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterModelTable(
            name='texttopdf',
            table='TextToPDF',
        ),
    ]
