# Generated by Django 4.2 on 2023-12-08 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc_to_pdf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='doctopdf',
            table='Doc To PDF',
        ),
    ]
