# Generated by Django 4.2 on 2023-12-10 17:07

import core.storage_backends
from django.db import migrations, models
import file_convert.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileConvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(storage=core.storage_backends.PublicMediaStorage(), upload_to='file-convert/')),
                ('file_size', file_convert.models.FileSizeField(blank=True, editable=False, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
            ],
            options={
                'db_table': 'file_convert',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
