# Generated by Django 4.2 on 2023-12-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_convert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileconvert',
            name='status',
            field=models.CharField(choices=[('none', 'None'), ('uploading', 'Uploading'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='none', max_length=20),
        ),
    ]
