version: '3.9'

services:
  chat-service:
    container_name: chat-service
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 8002:8002
    networks:
      - ms_hub_network
    volumes:
      - ./app/:/usr/src/app/
    # command: python manage.py runserver 0.0.0.0:8002
    # entrypoint: >
    #   sh -c "
    #     python manage.py migrate &&
    #     python manage.py runserver 0.0.0.0:8002 &&
    #     python manage.py init_kafka_consumer
    #   "
    entrypoint: >
      sh -c "
        # python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8002
      "

    depends_on:
      - redis
      - celery

  celery:
    build: ./app
    command: celery -A core worker --loglevel=INFO
    # env_file:
    #   - ./backend/app/.env 
    networks:
      - ms_hub_network
    volumes:
      - ./app/:/usr/src/app/
    environment: 
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  redis:
    container_name: redis
    image: "redis"
    ports:
      - 6379:6379
    networks:
      - ms_hub_network
networks:
  ms_hub_network:
    external: true


