# Generated by Django 4.2 on 2023-12-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hashed_password',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(verbose_name='password'),
        ),
    ]
