# Generated by Django 4.2 on 2023-12-02 18:44

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_hashed_password_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to=users.models.user_directory_path, verbose_name='profile photo'),
        ),
    ]
